# Generated by Django 5.2.14 on 2026-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Enterprise Client A", max_length=100),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP ERP Procurement"),
                            ("UTILITY", "Utility Portal"),
                            ("TRAVEL", "Corporate Travel Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.TextField()),
                (
                    "scope_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Scope 1", "Direct Emissions (Fuel)"),
                            ("Scope 2", "Indirect Emissions (Electricity)"),
                            ("Scope 3", "Other Indirect (Travel)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("normalized_value", models.FloatField(blank=True, null=True)),
                (
                    "normalized_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("calculated_co2e_kg", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved & Locked"),
                            ("FAILED", "Failed Error"),
                            ("SUSPICIOUS", "Suspicious Warning"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
