# Generated by Django 5.2.14 on 2026-05-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP ERP Procurement"),
                            ("UTILITY", "Utility Portal"),
                            ("TRAVEL", "Corporate Travel Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_payload", models.TextField()),
                (
                    "scope_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Scope 1", "Direct Emissions (Fuel)"),
                            ("Scope 2", "Indirect Emissions (Electricity)"),
                            ("Scope 3", "Other Indirect (Travel)"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("normalized_value", models.FloatField(blank=True, null=True)),
                (
                    "normalized_unit",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("calculated_co2e_kg", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved & Locked"),
                            ("FAILED", "Failed Error"),
                            ("SUSPICIOUS", "Suspicious Warning"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditTrailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(default="System_Analyst", max_length=100),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("previous_state", models.JSONField(blank=True, null=True)),
                ("new_state", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="emissions.activityrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="emissions.client",
            ),
        ),
    ]
